# Cloud Build configuration for Google Cloud Run
# Builds and deploys the backend service

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/biosynth-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/biosynth-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/biosynth-backend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/biosynth-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'biosynth-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/biosynth-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PORT=8080,ENVIRONMENT=production'

images:
  - 'gcr.io/$PROJECT_ID/biosynth-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/biosynth-backend:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

